
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Aug 23 15:02:53 CEST 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 37;
  public static final int LBRACKET = 18;
  public static final int CHAR = 42;
  public static final int CONST = 24;
  public static final int LPAREN = 14;
  public static final int SEMI = 25;
  public static final int CONTINUE = 21;
  public static final int FOR = 20;
  public static final int MINUS = 10;
  public static final int RPAREN = 15;
  public static final int AND = 31;
  public static final int LT = 36;
  public static final int OR = 30;
  public static final int BOOL = 43;
  public static final int COMMA = 26;
  public static final int INC = 6;
  public static final int DIV = 11;
  public static final int PLUS = 9;
  public static final int IF = 38;
  public static final int DOT = 27;
  public static final int EOF = 0;
  public static final int RETURN = 5;
  public static final int RBRACKET = 19;
  public static final int EQUAL = 8;
  public static final int NEW = 4;
  public static final int error = 1;
  public static final int MUL = 12;
  public static final int NUMBER = 41;
  public static final int MOD = 13;
  public static final int NEQ = 33;
  public static final int IDENT = 40;
  public static final int BREAK = 22;
  public static final int VOID = 28;
  public static final int EQ = 32;
  public static final int GTE = 35;
  public static final int ELSE = 39;
  public static final int LBRACE = 16;
  public static final int ENUM = 29;
  public static final int READ = 2;
  public static final int RBRACE = 17;
  public static final int PROG = 23;
  public static final int DEC = 7;
  public static final int GT = 34;
  public static final int PRINT = 3;
}

