
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Aug 08 15:42:45 CEST 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 13;
  public static final int READ = 2;
  public static final int IDENT = 29;
  public static final int PLUS = 9;
  public static final int RBRACE = 17;
  public static final int RPAREN = 15;
  public static final int EQUAL = 8;
  public static final int SEMI = 24;
  public static final int CHAR = 20;
  public static final int RETURN = 5;
  public static final int LBRACKET = 18;
  public static final int LPAREN = 14;
  public static final int LBRACE = 16;
  public static final int RBRACKET = 19;
  public static final int INC = 6;
  public static final int COMMA = 25;
  public static final int NUMBER = 30;
  public static final int EOF = 0;
  public static final int DIV = 11;
  public static final int PROG = 21;
  public static final int DEC = 7;
  public static final int MINUS = 10;
  public static final int DOT = 26;
  public static final int CONST = 23;
  public static final int ENUM = 22;
  public static final int PRINT = 3;
  public static final int error = 1;
  public static final int NEW = 4;
  public static final int BOOL = 28;
  public static final int VOID = 27;
  public static final int MUL = 12;
}

